FROM python:3.11-slim

ENV DRYRUN 'True'
ENV DEBUG 'True'
ENV DEBUG_LEVEL 'INFO'
ENV RUN_ONLY_ONCE 'False'
ENV SLEEP_DURATION '3600'
ENV LOGFILE 'log.log'
ENV MARKFILE 'mark.log'

ENV USER_MAPPING ''
ENV LIBRARY_MAPPING ''

ENV PLEX_BASEURL ''
ENV PLEX_TOKEN ''
ENV PLEX_USERNAME ''
ENV PLEX_PASSWORD ''
ENV PLEX_SERVERNAME ''

ENV JELLYFIN_BASEURL ''
ENV JELLYFIN_TOKEN ''

ENV SYNC_FROM_PLEX_TO_JELLYFIN 'True'
ENV SYNC_FROM_JELLYFIN_TO_PLEX 'True'
ENV SYNC_FROM_PLEX_TO_PLEX 'True'
ENV SYNC_FROM_JELLYFIN_TO_JELLYFIN 'True'

ENV BLACKLIST_LIBRARY ''
ENV WHITELIST_LIBRARY ''
ENV BLACKLIST_LIBRARY_TYPE  '' 
ENV WHITELIST_LIBRARY_TYPE  ''
ENV BLACKLIST_USERS  ''
ENV WHITELIST_USERS  ''


RUN addgroup --system jellyplex_user && \
    adduser --system --no-create-home jellyplex_user --ingroup jellyplex_user && \
    mkdir -p /app && \
    chown -R jellyplex_user:jellyplex_user /app

WORKDIR /app

COPY --chown=jellyplex_user:jellyplex_user ./requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY --chown=jellyplex_user:jellyplex_user . .

USER jellyplex_user

CMD ["python", "-u", "main.py"]
